#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 28, 2019 04:45:04 PM CET  platform: Windows NT
#    Dec 28, 2019 05:44:38 PM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
    import tkinter.filedialog

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

g_monitorDirectory = None
w, top_level, root = None, None, None
monitoredDirectory = None

def set_Tk_var():
    global monitoredDirectory
    monitoredDirectory = tk.StringVar()

def hostnameKeypress(p1):
    print('gui_support.hostnameKeypress')
    sys.stdout.flush()

def selectDirectory():
    print('gui_support.selectDirectory')
    global g_monitorDirectory
    g_monitorDirectory = tkinter.filedialog.askdirectory()
    monitoredDirectory.set(g_monitorDirectory)
    sys.stdout.flush()

def startMonitoring():
    print('gui_support.startMonitoring')
    sys.stdout.flush()

def stopMonitoring():
    print('gui_support.stopMonitoring')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gui
    gui.vp_start_gui()




