#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Dec 30, 2019 07:26:02 PM CET  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 739x645+463+186
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Enterprise File Monitor Manager"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr43 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$top.scr43" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1

    .top42.scr43.01 configure -columns Col1 \
        -height 4
        .top42.scr43.01 configure -columns {Col1}
        .top42.scr43.01 heading #0 -text {Tree}
        .top42.scr43.01 heading #0 -anchor center
        .top42.scr43.01 column #0 -width 200
        .top42.scr43.01 column #0 -minwidth 20
        .top42.scr43.01 column #0 -stretch 1
        .top42.scr43.01 column #0 -anchor w
        .top42.scr43.01 heading Col1 -text {Col1}
        .top42.scr43.01 heading Col1 -anchor center
        .top42.scr43.01 column Col1 -width 200
        .top42.scr43.01 column Col1 -minwidth 20
        .top42.scr43.01 column Col1 -stretch 1
        .top42.scr43.01 column Col1 -anchor w
    label $top.lab44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Hosts and agents} 
    vTcl:DefineAlias "$top.lab44" "Label1" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab42 \
        -font TkDefaultFont -foreground black \
        -text {Selected host/agent configuration} \
        -background $vTcl(actual_gui_bg) -height 325 -width 710 
    vTcl:DefineAlias "$top.lab42" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab42
    label $site_3_0.lab43 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Host: 
    vTcl:DefineAlias "$site_3_0.lab43" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab44 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text HostNameLabel 
    vTcl:DefineAlias "$site_3_0.lab44" "HostNameLabel" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Dir: 
    vTcl:DefineAlias "$site_3_0.lab45" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text DirNameLabel 
    vTcl:DefineAlias "$site_3_0.lab46" "DirNameLabel" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab43 \
        -in $site_3_0 -x 13 -y 26 -width 40 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 60 -y 26 -width 272 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 13 -y 49 -width 40 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 60 -y 50 -width 622 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.scr43 \
        -in $top -x 20 -y 70 -width 420 -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 20 -y 20 -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 20 -y 220 -width 710 -relwidth 0 -height 325 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

